version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    container_name: personal-notes-backend
    restart: always
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    container_name: personal-notes-frontend
    restart: always

